-- MySQL Script generated by MySQL Workbench
-- Fri Dec 13 09:44:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`exposicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exposicao` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(50) NOT NULL,
  `Tipo_Evento` ENUM('atividade diferenciada', 'atividade permanente') NOT NULL,
  `Descricao` VARCHAR(300) NOT NULL,
  `Quantidade_Inscritos` INT NOT NULL,
  `Data_Inicial` DATE NOT NULL,
  `Data_Final` DATE NULL DEFAULT NULL,
  `Link_Imagem` MEDIUMBLOB NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Titulo_UNIQUE` (`Titulo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agendamento` (
  `ID` INT UNSIGNED NULL AUTO_INCREMENT,
  `Turma` INT NOT NULL,
  `Visita` INT NOT NULL,
  `Data_Agendamento` DATETIME NOT NULL,
  `Exposicao` INT NOT NULL,
  `Status` ENUM('pendente', 'cancelado', 'confirmado') NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`visita` (
  `ID` INT UNSIGNED NOT NULL,
  `Agendamento` INT NULL DEFAULT NULL,
  `Data_Visita` DATE NOT NULL,
  `Turno` ENUM('manha', 'tarde', 'noite') NOT NULL,
  `ID_Acompanhante` INT NULL,
  `Status` ENUM('realizada', 'não realizada', 'instituição ausente') NOT NULL,
  `agendamento_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_visita_agendamento1_idx` (`agendamento_ID` ASC) VISIBLE,
  CONSTRAINT `fk_visita_agendamento1`
    FOREIGN KEY (`agendamento_ID`)
    REFERENCES `mydb`.`agendamento` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `tipo_usuario_ID` INT UNSIGNED NOT NULL,
  `visita_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuario_tipo_usuario_idx` (`tipo_usuario_ID` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  INDEX `fk_usuario_visita1_idx` (`visita_ID` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_ID`)
    REFERENCES `mydb`.`tipo_usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_visita1`
    FOREIGN KEY (`visita_ID`)
    REFERENCES `mydb`.`visita` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Permissao` (
  `ID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `Permissao` VARCHAR(40) NOT NULL,
  `tipo_usuario_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Permissao_tipo_usuario1_idx` (`tipo_usuario_ID` ASC) VISIBLE,
  UNIQUE INDEX `Permissao_UNIQUE` (`Permissao` ASC) VISIBLE,
  CONSTRAINT `fk_Permissao_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_ID`)
    REFERENCES `mydb`.`tipo_usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exposicao_agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exposicao_agendamento` (
  `ID` INT UNSIGNED NOT NULL,
  `exposicao` INT NOT NULL,
  `agendamento` INT NOT NULL,
  `exposicao_ID` INT NOT NULL,
  `agendamento_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_exposicao_agendamento_exposicao1_idx` (`exposicao_ID` ASC) VISIBLE,
  INDEX `fk_exposicao_agendamento_agendamento1_idx` (`agendamento_ID` ASC) VISIBLE,
  CONSTRAINT `fk_exposicao_agendamento_exposicao1`
    FOREIGN KEY (`exposicao_ID`)
    REFERENCES `mydb`.`exposicao` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exposicao_agendamento_agendamento1`
    FOREIGN KEY (`agendamento_ID`)
    REFERENCES `mydb`.`agendamento` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
  `ID` INT UNSIGNED NULL AUTO_INCREMENT,
  `Nome` VARCHAR(10) NOT NULL,
  `Professor_Int` INT NOT NULL,
  `Ano_Escolar` VARCHAR(12) NOT NULL,
  `Ensino` ENUM('Ensino Fundamental', 'Ensino Médio', 'Ensino Técnico', 'Ensino Superior') NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `ID` INT UNSIGNED NULL AUTO_INCREMENT,
  `Turma` INT NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `Idade` INT NOT NULL,
  `turma_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_aluno_turma1_idx` (`turma_ID` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_turma1`
    FOREIGN KEY (`turma_ID`)
    REFERENCES `mydb`.`turma` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`visitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`visitante` (
  `ID` INT UNSIGNED NULL AUTO_INCREMENT,
  `isAluno` TINYINT(1) NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `Status_Checkin` ENUM('compareceu', 'não compareceu') NOT NULL,
  `Idade` INT NOT NULL,
  `visita_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_visitante_visita1_idx` (`visita_ID` ASC) VISIBLE,
  CONSTRAINT `fk_visitante_visita1`
    FOREIGN KEY (`visita_ID`)
    REFERENCES `mydb`.`visita` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade_UF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidade_UF` (
  `ID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `tipo_usuario` SMALLINT NULL DEFAULT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `UF` CHAR(2) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `tipo_usuario_UNIQUE` (`tipo_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instituicao` (
  `ID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(6) NOT NULL,
  `cidade_UF` SMALLINT NOT NULL,
  `cep` CHAR(9) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `tipo_Instituicao` ENUM('Federal', 'Distrital', 'Estadual', 'Municipal', 'Privada', 'Filantrópica') NOT NULL,
  `cidade_UF_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_instituicao_cidade_UF_idx` (`cidade_UF_ID` ASC) VISIBLE,
  CONSTRAINT `fk_instituicao_cidade_UF`
    FOREIGN KEY (`cidade_UF_ID`)
    REFERENCES `mydb`.`cidade_UF` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor_instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor_instituicao` (
  `ID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `institucao` INT NOT NULL,
  `cont_Agendamento` SMALLINT NOT NULL,
  `cont_agendamento_cancelado` SMALLINT NOT NULL,
  `ativo` TINYINT NOT NULL,
  `instituicao_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_professor_instituicao_instituicao1_idx` (`instituicao_ID` ASC) VISIBLE,
  CONSTRAINT `fk_professor_instituicao_instituicao1`
    FOREIGN KEY (`instituicao_ID`)
    REFERENCES `mydb`.`instituicao` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
