-- MySQL Script generated by MySQL Workbench
-- qui 12 dez 2019 23:53:45 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`cidade_UF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cidade_UF` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cidade_UF` (
  `ID` INT UNSIGNED NULL AUTO_INCREMENT,
  `tipo_usuario` SMALLINT(2) NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `UF` CHAR(2) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `tipo_usuario_UNIQUE` (`tipo_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`instituicao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`instituicao` (
  `ID` INT(4) UNSIGNED NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(6) NOT NULL,
  `cidade_UF` SMALLINT(2) NOT NULL,
  `cep` CHAR(9) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `tipo_Instituicao` ENUM('Federal', 'Distrital', 'Estadual', 'Municipal', 'Privada', 'Filantrópica') NOT NULL,
  `cidade_UF_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_instituicao_cidade_UF_idx` (`cidade_UF_ID` ASC) VISIBLE,
  CONSTRAINT `fk_instituicao_cidade_UF`
    FOREIGN KEY (`cidade_UF_ID`)
    REFERENCES `mydb`.`cidade_UF` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor_instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`professor_instituicao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`professor_instituicao` (
  `ID` INT(4) UNSIGNED NULL AUTO_INCREMENT,
  `usuario` INT(4) NOT NULL,
  `institucao` INT(4) NOT NULL,
  `cont_Agendamento` SMALLINT(2) NOT NULL,
  `cont_agendamento_cancelado` SMALLINT(2) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `instituicao_ID` INT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_professor_instituicao_instituicao1_idx` (`instituicao_ID` ASC) VISIBLE,
  CONSTRAINT `fk_professor_instituicao_instituicao1`
    FOREIGN KEY (`instituicao_ID`)
    REFERENCES `mydb`.`instituicao` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `tipo_usuario_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuario_tipo_usuario_idx` (`tipo_usuario_ID` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_ID`)
    REFERENCES `mydb`.`tipo_usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Permissao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Permissao` (
  `ID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `Permissao` VARCHAR(40) NOT NULL,
  `tipo_usuario_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Permissao_tipo_usuario1_idx` (`tipo_usuario_ID` ASC) VISIBLE,
  UNIQUE INDEX `Permissao_UNIQUE` (`Permissao` ASC) VISIBLE,
  CONSTRAINT `fk_Permissao_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_ID`)
    REFERENCES `mydb`.`tipo_usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
